
install-go-deps:
	go get github.com/pressly/goose/v3/cmd/goose@latest
	go get github.com/jackc/pgx/v5/stdlib
	go get github.com/Masterminds/squirrel
	go get github.com/stretchr/testify/require
	go get github.com/ilyakaznacheev/cleanenv
	go get -u github.com/golang-jwt/jwt/v5